// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BitcoinWalletServiceClient is the client API for BitcoinWalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BitcoinWalletServiceClient interface {
	GenerateRandomMnemonic(ctx context.Context, in *RandomMnemonicRequest, opts ...grpc.CallOption) (*RandomMnemonicResponse, error)
	GenerateHDSegWitAddress(ctx context.Context, in *GenerateHDSegWitAddressRequest, opts ...grpc.CallOption) (*GenerateHDSegWitAddressResponse, error)
	GenerateMultiSigP2SHAddress(ctx context.Context, in *GenerateMultiSigP2SHAddressRequest, opts ...grpc.CallOption) (*GenerateMultiSigP2SHAddressResponse, error)
}

type bitcoinWalletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBitcoinWalletServiceClient(cc grpc.ClientConnInterface) BitcoinWalletServiceClient {
	return &bitcoinWalletServiceClient{cc}
}

func (c *bitcoinWalletServiceClient) GenerateRandomMnemonic(ctx context.Context, in *RandomMnemonicRequest, opts ...grpc.CallOption) (*RandomMnemonicResponse, error) {
	out := new(RandomMnemonicResponse)
	err := c.cc.Invoke(ctx, "/berkeozerr.GoWallet.BitcoinWalletService/GenerateRandomMnemonic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bitcoinWalletServiceClient) GenerateHDSegWitAddress(ctx context.Context, in *GenerateHDSegWitAddressRequest, opts ...grpc.CallOption) (*GenerateHDSegWitAddressResponse, error) {
	out := new(GenerateHDSegWitAddressResponse)
	err := c.cc.Invoke(ctx, "/berkeozerr.GoWallet.BitcoinWalletService/GenerateHDSegWitAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bitcoinWalletServiceClient) GenerateMultiSigP2SHAddress(ctx context.Context, in *GenerateMultiSigP2SHAddressRequest, opts ...grpc.CallOption) (*GenerateMultiSigP2SHAddressResponse, error) {
	out := new(GenerateMultiSigP2SHAddressResponse)
	err := c.cc.Invoke(ctx, "/berkeozerr.GoWallet.BitcoinWalletService/GenerateMultiSigP2SHAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BitcoinWalletServiceServer is the server API for BitcoinWalletService service.
// All implementations must embed UnimplementedBitcoinWalletServiceServer
// for forward compatibility
type BitcoinWalletServiceServer interface {
	GenerateRandomMnemonic(context.Context, *RandomMnemonicRequest) (*RandomMnemonicResponse, error)
	GenerateHDSegWitAddress(context.Context, *GenerateHDSegWitAddressRequest) (*GenerateHDSegWitAddressResponse, error)
	GenerateMultiSigP2SHAddress(context.Context, *GenerateMultiSigP2SHAddressRequest) (*GenerateMultiSigP2SHAddressResponse, error)
	mustEmbedUnimplementedBitcoinWalletServiceServer()
}

// UnimplementedBitcoinWalletServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBitcoinWalletServiceServer struct {
}

func (UnimplementedBitcoinWalletServiceServer) GenerateRandomMnemonic(context.Context, *RandomMnemonicRequest) (*RandomMnemonicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateRandomMnemonic not implemented")
}
func (UnimplementedBitcoinWalletServiceServer) GenerateHDSegWitAddress(context.Context, *GenerateHDSegWitAddressRequest) (*GenerateHDSegWitAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateHDSegWitAddress not implemented")
}
func (UnimplementedBitcoinWalletServiceServer) GenerateMultiSigP2SHAddress(context.Context, *GenerateMultiSigP2SHAddressRequest) (*GenerateMultiSigP2SHAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateMultiSigP2SHAddress not implemented")
}
func (UnimplementedBitcoinWalletServiceServer) mustEmbedUnimplementedBitcoinWalletServiceServer() {}

// UnsafeBitcoinWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BitcoinWalletServiceServer will
// result in compilation errors.
type UnsafeBitcoinWalletServiceServer interface {
	mustEmbedUnimplementedBitcoinWalletServiceServer()
}

func RegisterBitcoinWalletServiceServer(s grpc.ServiceRegistrar, srv BitcoinWalletServiceServer) {
	s.RegisterService(&BitcoinWalletService_ServiceDesc, srv)
}

func _BitcoinWalletService_GenerateRandomMnemonic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomMnemonicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitcoinWalletServiceServer).GenerateRandomMnemonic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berkeozerr.GoWallet.BitcoinWalletService/GenerateRandomMnemonic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitcoinWalletServiceServer).GenerateRandomMnemonic(ctx, req.(*RandomMnemonicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BitcoinWalletService_GenerateHDSegWitAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateHDSegWitAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitcoinWalletServiceServer).GenerateHDSegWitAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berkeozerr.GoWallet.BitcoinWalletService/GenerateHDSegWitAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitcoinWalletServiceServer).GenerateHDSegWitAddress(ctx, req.(*GenerateHDSegWitAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BitcoinWalletService_GenerateMultiSigP2SHAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateMultiSigP2SHAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitcoinWalletServiceServer).GenerateMultiSigP2SHAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berkeozerr.GoWallet.BitcoinWalletService/GenerateMultiSigP2SHAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitcoinWalletServiceServer).GenerateMultiSigP2SHAddress(ctx, req.(*GenerateMultiSigP2SHAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BitcoinWalletService_ServiceDesc is the grpc.ServiceDesc for BitcoinWalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BitcoinWalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "berkeozerr.GoWallet.BitcoinWalletService",
	HandlerType: (*BitcoinWalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateRandomMnemonic",
			Handler:    _BitcoinWalletService_GenerateRandomMnemonic_Handler,
		},
		{
			MethodName: "GenerateHDSegWitAddress",
			Handler:    _BitcoinWalletService_GenerateHDSegWitAddress_Handler,
		},
		{
			MethodName: "GenerateMultiSigP2SHAddress",
			Handler:    _BitcoinWalletService_GenerateMultiSigP2SHAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet_processor.proto",
}
